apiVersion: apps/v1
kind: Deployment
metadata:
  name: rita-backend-deployment
  labels:
    app: rita-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rita-backend
  template:
    metadata:
      labels:
        app: rita-backend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: rita-backend
          image: ghcr.io/lucasmaraz/rita-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: VITE_BACKEND_PRODUCTOS
              valueFrom:
                configMapKeyRef:
                  name: backend-rita-config
                  key: VITE_BACKEND_PRODUCTOS
            - name: VITE_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-rita-config
                  key: VITE_ADMIN_USER