apiVersion: apps/v1
kind: Deployment
metadata:
  name: rita-deployment
  namespace: default
  labels:
    app: rita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rita
  template:
    metadata:
      labels:
        app: rita
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: rita
          image: ghcr.io/lucasmaraz/rita-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: frontend-config-volume
              mountPath: /usr/share/nginx/html/config
      volumes:
        - name: frontend-config-volume
          configMap:
            name: frontend-config